(function (root) {
  'use strict';
  const instrument = {
    version: '1.8.0',
    title: 'Validación de expertos',
    researcherEmail: 'luis.gonzalezc@urjc.es',
    purpose: 'Identificar brechas de evidencia y de capacidad de ejecución para priorizar el siguiente hito de una startup en fase temprana.',
    population: 'Startups desde la exploración de una idea hasta las primeras señales de repetición comercial. La pertinencia de cada pregunta depende de la fase y del modelo de negocio.',
    source: 'Revisión de V1.7. Conserva las seis dimensiones, veinte preguntas y dos juicios por pregunta. V1.8 reduce el cierre a una observación final y añade entrega desde el formulario; candidata pendiente de validación.',
    expertCriteria: { relevance: 'Relevancia de la pregunta, de 1 a 4.', usability: 'Valoración conjunta de claridad de la pregunta y adecuación de sus respuestas, de 1 a 4. Los problemas específicos se explican en Observaciones.' },
    dimensions: [
      { id: 'D1', short: 'Equipo', name: 'Equipo y gobernanza', desc: 'Capacidades disponibles, aprendizaje, dedicación y acuerdos para ejecutar el siguiente hito.' },
      { id: 'D2', short: 'Mercado', name: 'Problema y mercado', desc: 'Segmento prioritario, evidencia del problema, mercado accesible y condiciones de adopción.' },
      { id: 'D3', short: 'Propuesta de valor', name: 'Propuesta de valor y modelo de negocio', desc: 'Ventaja percibida, hipótesis de monetización y resultados de las pruebas de la solución.' },
      { id: 'D4', short: 'Evidencia comercial', name: 'Evidencia comercial', desc: 'Compromisos verificables y pruebas de adquisición de clientes en el segmento elegido.' },
      { id: 'D5', short: 'Finanzas', name: 'Evidencia financiera', desc: 'Control de caja, previsión, recursos para el siguiente hito y economía del cliente cuando sea aplicable.' },
      { id: 'D6', short: 'Recursos y confianza', name: 'Recursos estratégicos y legitimidad', desc: 'Relaciones y evidencias de confianza que facilitan recursos, acceso al mercado o acuerdos.' }
    ],
    items: [
      { id: 'T1', dim: 'D1', q: '¿Están disponibles las capacidades necesarias para ejecutar el siguiente hito?',
        note: 'Incluya capacidades internas o externas. Externalizar no implica menor capacidad; valore disponibilidad y dependencias críticas.',
        levels: ['No se han identificado las capacidades necesarias o faltan capacidades que bloquean el hito.', 'Se han identificado las carencias, pero su cobertura todavía no está asegurada.', 'Las capacidades necesarias están disponibles y hay responsables para las tareas críticas.', 'Su coordinación ya ha permitido cumplir hitos comparables y se gestionan las dependencias críticas.'] },
      { id: 'T2', dim: 'D1', q: '¿El equipo dispone de conocimiento directo del cliente, sector o problema para tomar decisiones?',
        note: 'Puede proceder de experiencia previa, investigación directa o colaboración continuada con personas conocedoras del contexto.',
        levels: ['Las decisiones se apoyan principalmente en supuestos sin contraste directo.', 'Hay conocimiento indirecto o contactos puntuales, con lagunas relevantes.', 'El equipo dispone de conocimiento directo sobre el cliente y su contexto.', 'Ese conocimiento ha permitido corregir supuestos y fundamentar decisiones concretas.'] },
      { id: 'T3', dim: 'D1', q: '¿El equipo convierte la evidencia y los aprendizajes en decisiones sobre el proyecto?',
        note: 'Considere un ejemplo reciente de una decisión confirmada o modificada a partir de una prueba. No se exige haber fundado antes otra empresa.',
        levels: ['No se identifican hipótesis ni aprendizajes concretos.', 'Se comentan aprendizajes, pero no se relacionan con decisiones.', 'Se registran pruebas o experiencias y las decisiones que se toman a partir de ellas.', 'Se revisan sistemáticamente los resultados y se ajustan prioridades cuando la evidencia lo requiere.'] },
      { id: 'T4', dim: 'D1', q: '¿La dedicación disponible permite ejecutar las prioridades de esta fase?',
        note: 'Valore las últimas cuatro semanas o, si el proyecto es más reciente, el periodo desde su inicio. No se exige dedicación exclusiva.',
        levels: ['La falta de tiempo bloquea las prioridades principales.', 'Hay tiempo disponible, pero se incumplen repetidamente las tareas prioritarias.', 'La dedicación permite ejecutar las tareas principales del periodo.', 'La dedicación se planifica y ajusta para cumplir los hitos comprometidos de forma consistente.'] },
      { id: 'T5', dim: 'D1', q: '¿Están claros y documentados los acuerdos necesarios para tomar decisiones y distribuir responsabilidades?',
        note: 'Adapte al equipo: con varios fundadores, participaciones, responsabilidades y salidas; con fundador único, responsabilidades, delegación y acuerdos con colaboradores. El vesting solo se considera si procede.',
        levels: ['No están claros los responsables ni cómo se toman decisiones importantes.', 'Existen acuerdos verbales o parciales sobre responsabilidades y decisiones.', 'Los acuerdos relevantes para la estructura actual están documentados y son conocidos.', 'Se revisan ante cambios del equipo y contemplan cómo resolver desacuerdos, ausencias o salidas.'] },
      { id: 'PM1', dim: 'D2', q: '¿Está definido el segmento prioritario al que se dirigen las pruebas y acciones comerciales?',
        note: 'Cuando sean diferentes, distinga usuario, comprador y pagador.',
        levels: ['El mercado objetivo es amplio y no hay un segmento concreto.', 'Se han identificado segmentos posibles, sin prioridad justificada.', 'Existe un segmento prioritario descrito con criterios que permiten identificar clientes.', 'Las pruebas y acciones se concentran en ese segmento y la elección se revisa con evidencia.'] },
      { id: 'PM2', dim: 'D2', q: '¿Hay evidencia directa de que el problema es suficientemente importante para que el cliente actúe?',
        note: 'La importancia puede provenir del coste, frecuencia, riesgo o urgencia. Un problema infrecuente también puede ser relevante.',
        levels: ['No hay evidencia directa del problema.', 'Hay opiniones o interés declarado, sin ejemplos concretos de sus consecuencias.', 'Personas del segmento, también fuera del círculo cercano, describen casos y consecuencias concretas.', 'En distintos casos se observan esfuerzos, gasto o cambios de comportamiento para resolverlo.'] },
      { id: 'PM3', dim: 'D2', q: '¿La estimación del mercado accesible se apoya en supuestos y datos contrastables?',
        note: 'Puede combinar una estimación top-down con datos de clientes, precios y canales. Valore la trazabilidad y los límites de los supuestos.',
        levels: ['No existe una estimación útil del mercado accesible.', 'Hay una cifra general, sin supuestos claros sobre clientes o acceso.', 'La estimación explicita clientes alcanzables, precios o frecuencia y restricciones de acceso.', 'Los supuestos se contrastan con datos del segmento y se revisan cuando aparece nueva evidencia.'] },
      { id: 'PM4', dim: 'D2', q: '¿Se conocen las condiciones que facilitan o dificultan que el segmento adopte la solución ahora?',
        note: 'Incluya hábitos, costes de cambio, tecnología, regulación o ciclos de compra. Un mercado estable puede ser adecuado.',
        levels: ['No se han analizado las condiciones de adopción.', 'Se han identificado posibles facilitadores o barreras, principalmente por intuición.', 'Se han contrastado facilitadores y barreras con personas o datos del segmento.', 'Las pruebas de adopción permiten ajustar la propuesta, el momento o el proceso de entrada.'] },
      { id: 'VB1', dim: 'D3', q: '¿El cliente reconoce una ventaja concreta frente a las alternativas que utiliza hoy?',
        note: 'Incluya competidores, sustitutos, soluciones improvisadas (workarounds) y la opción de no hacer nada.',
        levels: ['No se conocen suficientemente las alternativas actuales.', 'La ventaja propuesta es principalmente una hipótesis interna.', 'Personas del segmento reconocen una ventaja específica frente a sus alternativas.', 'Esa ventaja explica decisiones observadas de uso, elección o compra en distintos casos.'] },
      { id: 'VB2', dim: 'D3', q: '¿Está contrastado quién pagaría, por qué concepto y bajo qué condiciones?',
        note: 'Evalúe la lógica de monetización. Los pagos y compromisos reales se examinan específicamente en C1.',
        levels: ['No se identifica con claridad quién pagaría ni por qué concepto.', 'Existe una hipótesis de pagador, precio y forma de cobro.', 'La hipótesis se ha contrastado con posibles pagadores y se conocen sus objeciones.', 'Las pruebas de oferta o negociación han permitido ajustar precio, condiciones y forma de cobro.'] },
      { id: 'VB3', dim: 'D3', q: '¿Las pruebas con usuarios reales muestran que la solución produce el resultado que promete?',
        applicabilityNote: 'Si el uso es puntual, no se exige repetición: valore si el resultado se confirma en distintos casos. No haber realizado pruebas se refleja en el nivel 0; no equivale a «No aplica».',
        note: 'El resultado puede ser ahorro de tiempo, reducción de errores u otro beneficio relevante. Adapte continuidad, repetición o retención al modelo.',
        levels: ['La solución todavía no se ha probado con usuarios del segmento.', 'Se ha mostrado un concepto o demo, sin observar el resultado de uso.', 'Usuarios del segmento han probado la solución y se ha observado el resultado obtenido.', 'El resultado se confirma en distintos casos y hay continuidad o repetición de uso cuando corresponde.'] },
      { id: 'C1', dim: 'D4', q: '¿Qué grado de compromiso comercial verificable ha obtenido la startup?',
        note: 'Diferencie interés, LOI, piloto con recursos comprometidos y pago. Un pago aislado no demuestra repetibilidad; anote contexto y condiciones.',
        levels: ['No hay señales comerciales documentadas.', 'Hay interés o conversaciones documentadas, sin recursos comprometidos.', 'Hay compromisos verificables de tiempo, acceso, recursos o compra, con alcance y condiciones explícitas.', 'Hay pagos o contratos de compra verificables, con importe, alcance y condiciones identificados.'] },
      { id: 'C2', dim: 'D4', q: '¿Se ha probado una forma de llegar y vender al segmento prioritario?',
        applicabilityNote: 'En ciclos comerciales largos pueden utilizarse avances verificables del proceso, aunque todavía no haya ventas. No haber probado el canal es una brecha de evidencia, no un «No aplica».',
        note: 'GTM: estrategia de llegada al mercado. Valore pruebas y resultados en relación con la duración del ciclo comercial.',
        levels: ['No hay una hipótesis concreta de canal o proceso comercial.', 'Existe una hipótesis de canal, mensaje y forma de venta para el segmento.', 'Se ha probado con clientes reales y se registran contactos, conversiones u otros resultados pertinentes.', 'Pruebas sucesivas muestran resultados comparables y permiten ajustar el proceso comercial.'] },
      { id: 'F1', dim: 'D5', q: '¿Se conoce la caja disponible y cómo evoluciona con los cobros y pagos previstos?',
        note: 'Incluya burn neto y runway cuando exista consumo neto de caja. Si los cobros cubren los pagos, no fuerce un runway finito.',
        levels: ['No se conoce la caja disponible o los principales cobros y pagos.', 'Hay estimaciones aproximadas, sin conciliación con los movimientos reales.', 'La caja y los movimientos se registran y se conoce la necesidad de financiación a corto plazo.', 'La información se actualiza al menos mensualmente y se utiliza para decidir gastos y compromisos.'] },
      { id: 'F2', dim: 'D5', q: '¿Existe una previsión de caja que permita anticipar las necesidades de los próximos meses?',
        note: 'Como referencia, considere los próximos seis meses o el horizonte del siguiente hito cuando resulte más adecuado.',
        levels: ['No existe una previsión.', 'Hay una estimación informal de entradas y salidas.', 'Existe una previsión con supuestos explícitos sobre cobros, pagos y saldo de caja.', 'Se revisa frente a los datos reales y contempla escenarios para anticipar decisiones.'] },
      { id: 'F3', dim: 'D5', q: '¿Se conocen los recursos necesarios y su financiación para alcanzar el siguiente hito?',
        note: 'Incluya recursos propios, ingresos, ayudas u otras fuentes. No se presupone la necesidad de inversión externa.',
        levels: ['No está definido el siguiente hito o los recursos que requiere.', 'Hay una estimación de recursos sin conexión suficiente con las tareas del hito.', 'Se relacionan tareas, costes y recursos disponibles, identificando la posible brecha de financiación.', 'Se ajustan los recursos y el plan de financiación según el avance y la evidencia obtenida.'] },
      { id: 'F4', dim: 'D5', q: 'Cuando hay datos suficientes, ¿se conoce la relación entre el coste de adquirir y servir al cliente y el margen que aporta?',
        note: 'CAC y LTV son opciones cuando el modelo y los datos permiten estimarlos con sentido. Juzgue también si está clara la distinción entre una estimación preliminar y la falta de base para estimar.',
        conditional: 'No aplica todavía: si la fase del proyecto no permite una estimación fundamentada con datos o supuestos explícitos. Se registraría aparte, nunca como 0. Si hay datos suficientes pero no se analizan, corresponde el nivel 0.',
        levels: ['No se han analizado los costes de adquirir y servir al cliente ni el margen que aporta.', 'Existen estimaciones preliminares con supuestos y limitaciones identificados.', 'Se calculan costes y margen con datos reales para un segmento o grupo de clientes comparable.', 'Se revisan los cálculos y su incertidumbre para orientar precios, adquisición o servicio.'] },
      { id: 'SA1', dim: 'D6', q: '¿Las relaciones externas aportan recursos u oportunidades necesarios para el siguiente hito?',
        note: 'Valore contribuciones, no prestigio ni tamaño de la red. Incluya proveedores, clientes, comunidades, especialistas y colaboradores.',
        levels: ['No se han identificado las relaciones externas necesarias.', 'Hay contactos posibles, sin una contribución concreta acordada.', 'Existen contribuciones verificables vinculadas a necesidades del proyecto.', 'Las contribuciones se mantienen y facilitan avances concretos, gestionando dependencias.'] },
      { id: 'SA2', dim: 'D6', q: '¿Existen evidencias de confianza adecuadas a lo que necesitan clientes o socios para colaborar?',
        note: 'Pueden ser referencias, resultados de pruebas, experiencia demostrada o acreditaciones pertinentes. No se exige tener inversores ni apoyos prestigiosos.',
        levels: ['No se conoce qué evidencias de confianza necesita el cliente o socio.', 'Se conocen esas necesidades, pero solo hay afirmaciones o señales informales.', 'Hay referencias, resultados u otras evidencias verificables pertinentes para esas necesidades.', 'Esas evidencias han facilitado acuerdos, acceso o colaboración en casos concretos.'] }
    ],
    glossary: [
      { term: 'vesting', label: 'Vesting', definition: 'Adquisición progresiva de derechos sobre participaciones, sujeta a plazos o condiciones acordadas.' },
      { term: 'burn', label: 'Burn neto', definition: 'Consumo neto de caja durante un periodo: salidas menos entradas. Si no hay consumo neto positivo, el runway simple no se calcula de la misma manera.' },
      { term: 'runway', label: 'Runway', definition: 'Meses de caja disponibles bajo un escenario de consumo neto. Es una estimación dependiente de los supuestos, no una fecha garantizada.' },
      { term: 'cac', label: 'CAC', definition: 'Coste de adquisición de un cliente. Debe especificar qué costes incluye, el canal y el periodo considerado.' },
      { term: 'ltv', label: 'LTV', definition: 'Estimación de la contribución económica de un cliente durante su relación. Conviene explicitar margen, permanencia y limitaciones de los datos.' },
      { term: 'loi', label: 'LOI', definition: 'Carta de intención que expresa interés o condiciones preliminares. Su fuerza como evidencia depende del contenido y de los compromisos asumidos.' },
      { term: 'gtm', label: 'GTM', definition: 'Go-to-market: cómo se llega al segmento, se comunica el valor y se convierte el interés en una relación comercial.' },
      { term: 'top-down', label: 'Top-down', definition: 'Estimación que parte de cifras generales de mercado y acota la parte accesible mediante supuestos.' },
      { term: 'workarounds', label: 'Workarounds', definition: 'Soluciones improvisadas o combinaciones de herramientas que el cliente ya utiliza para resolver el problema.' }
    ]
  };
  if (typeof module !== 'undefined' && module.exports) module.exports = instrument;
  else root.ValidationInstrument = instrument;
})(globalThis);
