(function (root) {
  'use strict';
  const item=(id,dim,q,levels,note='')=>({id,dim,q,levels,note});
  const instrument={
    version:'2.5.0',schema:'expert-validation/2.5',title:'Diagnóstico de startups en fases iniciales',researcherEmail:'luis.gonzalezc@urjc.es',
    purpose:'Ofrecer a las startups en fases iniciales y a quienes las acompañan o evalúan (inversores, mentores e incubadoras) un análisis de situación que permita identificar riesgos o debilidades, fortalezas y oportunidades.',
    population:'Startups en fases iniciales, desde la exploración de una idea hasta las primeras ventas y señales de repetición comercial.',
    source:'Instrumento V2.5 revisado el 16 de septiembre de 2026. Banco de 20 ítems; pendiente de validación experta.',
    expertCriteria:{relevance:'Relevancia de 1 a 4; obligatoria al enviar, salvo omisión explícita.',usability:'Claridad y respuestas, de 1 a 4; opcional para todos los ítems.'},
    dimensions:[
      {id:'D1',short:'Equipo',name:'Equipo',desc:'Capacidades, conocimiento, disponibilidad y aprendizaje del equipo para ejecutar el proyecto.'},
      {id:'D2',short:'Adaptación al mercado',name:'Adaptación al mercado',desc:'Comprensión del cliente, problema y mercado, diferenciación, monetización y evidencia de que la solución genera valor y puede evolucionar.'},
      {id:'D4',short:'Marketing y ventas',name:'Marketing y ventas',desc:'Evidencias de compromiso comercial y capacidad para llegar, vender y aprender del proceso comercial.'},
      {id:'D5',short:'Gestión financiera',name:'Gestión financiera',desc:'Control de la situación financiera, previsión de caja, recursos para avanzar y economía del cliente.'},
      {id:'D6',short:'Gestión de recursos y relaciones',name:'Gestión de recursos y relaciones',desc:'Relaciones externas y señales de confianza que permiten acceder a recursos, conocimiento, mercado y oportunidades.'}
    ],
    items:[
      item('E1','D1','¿El equipo tiene los perfiles necesarios y complementarios para ejecutar el proyecto?',['No se ha analizado qué perfiles o capacidades necesita el proyecto.','Se conocen las principales carencias, pero algunas funciones críticas siguen sin cubrir.','Las funciones críticas están cubiertas y existe una persona responsable de cada una.','El equipo ya ha demostrado que puede ejecutar hitos relevantes y las capacidades externas necesarias están cubiertas de forma estable.'],'Considerar producto, tecnología, operaciones, ventas u otras capacidades específicas del modelo de negocio. No es necesario que todas estén dentro del equipo fundador.'),
      item('E2','D1','¿El equipo conoce de primera mano al cliente, el sector y el problema que intenta resolver?',['Las decisiones se basan principalmente en supuestos internos.','Existe conocimiento indirecto o contacto ocasional con clientes o personas del sector.','El equipo tiene experiencia o contacto directo con el mercado y entiende cómo actúan, compran o resuelven actualmente el problema los clientes.','Este conocimiento se actualiza regularmente y ya ha permitido corregir supuestos o cambiar decisiones importantes.'],'No se exige experiencia profesional previa en el sector. El conocimiento puede obtenerse mediante experiencia, investigación o contacto continuado con clientes.'),
      item('E3','D1','¿La disponibilidad real del equipo permite ejecutar las prioridades de esta fase?',['La falta de disponibilidad bloquea las prioridades principales.','Se pueden atender algunas prioridades, pero otras se retrasan de forma recurrente.','La disponibilidad es suficiente para ejecutar las prioridades actuales.','La dedicación se mantiene incluso ante periodos de mayor carga y permite cumplir los principales compromisos del proyecto.']),
      item('E4','D1','¿El equipo convierte la evidencia y los aprendizajes en decisiones sobre el proyecto?',['No se identifican aprendizajes o hipótesis concretas.','Se obtiene información y feedback, pero su impacto sobre las decisiones es limitado.','Las pruebas y aprendizajes se relacionan con decisiones concretas sobre el proyecto.','Los resultados se revisan sistemáticamente y las prioridades cambian cuando la evidencia contradice las hipótesis iniciales.'],'La evidencia puede proceder de entrevistas, uso, ventas, experimentos u operaciones. Lo importante es que influya en decisiones concretas.'),
      item('AM1','D2','¿Está claramente definido el segmento de clientes prioritario?',['El mercado objetivo es amplio y no existe un segmento concreto.','Se han identificado varios segmentos posibles, pero no existe una prioridad clara.','Existe un segmento prioritario definido con criterios que permiten identificar a sus clientes.','Las pruebas y acciones se concentran en ese segmento y su elección se revisa utilizando evidencia.'],'Cuando sean diferentes, distinguir entre usuario, comprador y pagador.'),
      item('AM2','D2','¿Existe evidencia de que el problema es suficientemente importante para que el cliente actúe?',['No existe evidencia directa del problema.','Los clientes expresan interés o reconocen el problema, pero sin consecuencias concretas.','Personas del segmento describen ejemplos reales y consecuencias relevantes en tiempo, dinero, riesgo o esfuerzo.','En distintos casos se observa que los clientes ya dedican recursos, tiempo, dinero o soluciones alternativas para resolverlo.'],'Una declaración de interés es una señal débil. Tienen más peso los comportamientos observados y los recursos que el cliente ya dedica a resolver el problema.'),
      item('AM3','D2','¿Se conoce suficientemente el mercado al que puede acceder realmente la startup?',['No existe un análisis útil del mercado accesible.','Se manejan cifras generales o estimaciones con pocos supuestos contrastados.','Se conocen los clientes potencialmente alcanzables, precios, frecuencia de compra, principales segmentos y barreras de entrada.','Los supuestos se contrastan con datos recientes y se revisan cuando cambia el mercado.'],'Priorizar estimaciones construidas desde clientes potenciales reales frente a limitarse a aplicar porcentajes sobre grandes cifras globales de mercado.'),
      item('AM5','D2','¿Se conocen las principales alternativas del cliente y existe una ventaja difícil de replicar?',['No se conocen suficientemente los competidores, sustitutos o alternativas actuales.','Se conocen las principales alternativas, pero la diferenciación es todavía una hipótesis o sería relativamente fácil de copiar.','Los clientes reconocen una ventaja concreta y replicarla requiere tiempo, conocimiento, recursos u otras capacidades relevantes.','La ventaja influye en decisiones reales de uso o compra y se apoya en varias barreras difíciles de reproducir.'],'Las barreras pueden provenir de tecnología, datos, conocimiento especializado, marca, comunidad, red, acuerdos, costes de cambio u otros activos. No se exige disponer de una patente.'),
      item('AM4','D2','¿Se monitorizan los cambios del mercado que podrían afectar al éxito del proyecto?',['No se realiza un seguimiento específico.','Se observan ocasionalmente tendencias, competidores o cambios relevantes.','Se revisan periódicamente clientes, competencia, tecnología, regulación, hábitos u otros cambios relevantes.','Estas señales se relacionan con los resultados del producto y provocan cambios en la estrategia cuando es necesario.'],'Considerar cambios en clientes, competidores, tecnología, regulación, costes o hábitos. No basta con observarlos: deben relacionarse con decisiones del proyecto.'),
      item('AM6','D2','¿Está definido y contrastado quién paga, por qué paga y cómo lo hace?',['No está claro quién pagaría ni por qué concepto.','Existe una hipótesis sobre pagador, precio y forma de cobro.','La hipótesis se ha contrastado con posibles pagadores y se conocen sus principales objeciones.','Pruebas de oferta, negociación o venta han permitido ajustar el precio y las condiciones comerciales.'],'Cuando sean distintos, separar usuario, comprador y pagador. La forma de pago puede ser puntual, recurrente, por uso, por resultados u otra adecuada al modelo.'),
      item('AM8','D2','¿Las funcionalidades se priorizan y mejoran utilizando evidencia de los usuarios?',['Las funcionalidades se deciden principalmente por intuición o ideas internas.','Existe una lista de funcionalidades y se recoge feedback, pero la priorización es poco sistemática.','Las funcionalidades se priorizan mediante criterios claros y utilizando feedback de usuarios.','Después de introducir cambios se comprueba su impacto y se vuelve a priorizar utilizando feedback, comportamiento o métricas.'],"Puede utilizarse una metodología como MoSCoW: Must have, Should have, Could have, Won't have. Pero no es obligatorio utilizar esta metodología. El instrumento mide la existencia de una priorización razonada basada en evidencia, no el uso de una herramienta concreta."),
      item('MV1','D4','¿Qué grado de compromiso comercial real ha conseguido la startup?',['No existen compromisos comerciales documentados.','Existe interés, conversaciones o intenciones de compra, pero sin recursos comprometidos.','Existen compras, pilotos, contratos u otros compromisos verificables de recursos.','Se observa repetición: nuevas ventas, renovaciones, compras recurrentes o repetición del proceso comercial con distintos clientes.'],'Interesa la evidencia de comportamiento. Una intención verbal tiene menos valor que dedicar tiempo, datos, recursos o dinero.'),
      item('MV2','D4','¿Se ha probado un canal de venta concreto para llegar al segmento prioritario y conseguir clientes?',['No existe una hipótesis concreta de canal o proceso comercial.','Existe una hipótesis sobre canal, mensaje y proceso de venta.','Se ha probado con clientes reales y se registran contactos, conversiones u otros resultados relevantes.','Pruebas sucesivas ofrecen resultados comparables y se conoce aproximadamente el tiempo y coste necesarios para conseguir clientes.'],'El canal de venta es la vía utilizada para llegar al cliente y convertir oportunidades en ventas. Adaptar las señales al ciclo comercial; en B2B complejo puede durar meses.'),
      item('MV3','D4','¿Se registran las oportunidades comerciales y las razones por las que avanzan, se detienen o se pierden?',['No existe un seguimiento estructurado de las oportunidades.','Se registran algunos contactos u oportunidades, pero de forma irregular.','Existe un seguimiento sistemático del estado de las oportunidades y de sus resultados.','Se analizan patrones de avance, pérdida y conversión y se utilizan para mejorar el proceso comercial.'],'No es necesario utilizar un CRM. Una hoja de cálculo puede ser suficiente si el seguimiento es consistente.'),
      item('GF1','D5','¿Se conoce el dinero disponible y los principales cobros y pagos de la startup?',['No se conoce con precisión la caja disponible o los principales movimientos.','Existen estimaciones aproximadas, pero no se actualizan de forma consistente.','La caja, cobros y pagos se registran y se conoce la situación financiera actual.','La información se actualiza periódicamente y se utiliza para decidir gastos y compromisos.'],'Se evalúa el control de caja necesario para decidir, no la existencia de una contabilidad sofisticada.'),
      item('GF2','D5','¿Existe una previsión que permita anticipar las necesidades financieras de los próximos meses?',['No existe una previsión.','Existe una estimación aproximada de ingresos y gastos futuros.','Existe una previsión de caja basada en supuestos explícitos y se conoce durante cuánto tiempo pueden mantenerse las operaciones.','La previsión se actualiza con datos reales y se utilizan diferentes escenarios para anticipar decisiones.'],'GF1 responde: ¿Dónde estamos hoy? GF2 responde: ¿Qué puede ocurrir durante los próximos meses?'),
      item('GF3','D5','¿Se conocen los recursos necesarios y cómo se financiarán para alcanzar el siguiente hito?',['No está definido el siguiente hito ni los recursos que requiere.','El siguiente hito está identificado, pero sus necesidades de recursos o financiación son aproximadas.','Se conocen los recursos necesarios, su coste y las principales fuentes para financiarlos.','Existe margen o un plan contrastado para financiar el hito y se revisa cuando cambian los resultados.'],'La financiación puede proceder de ventas, recursos propios, socios, deuda, ayudas o inversión. No se presupone que una startup deba captar capital riesgo.'),
      item('GF4','D5','¿Se conoce cuánto cuesta conseguir y atender a un cliente y qué margen genera?',['No se conocen suficientemente los costes o ingresos asociados a un cliente.','Existen estimaciones iniciales basadas principalmente en supuestos.','Existen datos o estimaciones contrastadas sobre adquisición, atención, ingresos y margen por cliente.','Estos datos se revisan periódicamente y se utilizan para tomar decisiones sobre precios, canales, costes o crecimiento.'],'Adaptar las métricas al modelo de negocio. No es obligatorio utilizar CAC/LTV si esas métricas no son adecuadas para el modelo.'),
      item('GR1','D6','¿La startup ha desarrollado colaboraciones que aporten recursos o ventajas relevantes?',['No existen colaboraciones relevantes.','Existen contactos o colaboraciones informales, pero su impacto es limitado.','Existen colaboraciones activas que facilitan recursos, conocimiento, clientes, innovación, eficiencia o reducción de costes.','Algunas colaboraciones generan ventajas claras y medibles y son relevantes para avanzar o crecer.'],'Pueden incluir proveedores, universidades, aceleradoras, empresas, distribuidores, comunidades, instituciones u otros actores relevantes.'),
      item('GR2','D6','¿La startup ha conseguido clientes o colaboradores que refuercen su legitimidad en el mercado y faciliten el acceso a recursos u oportunidades?',['Todavía no existen clientes o colaboradores que aporten legitimidad externa.','Existen primeros clientes, pilotos o colaboraciones, pero aún generan pocas oportunidades adicionales.','La relación con clientes o colaboradores reconocidos aumenta la confianza de terceros y facilita acceso a recursos, contactos o nuevas oportunidades.','Estas relaciones generan de forma demostrable nuevas ventas, alianzas, distribución, financiación, conocimiento u otros recursos relevantes.'],'GR1 evalúa lo que aportan directamente las colaboraciones. Esta pregunta evalúa si clientes o colaboradores también actúan como señal de confianza y abren nuevas puertas en el mercado.')
    ],glossary:[]
  };
  if(typeof module!=='undefined'&&module.exports)module.exports=instrument;else root.ValidationInstrument=instrument;
})(globalThis);
