(function (root) {
  'use strict';
  const item=(id,dim,q,levels,note='')=>({id,dim,q,levels,note});
  const instrument={
    version:'2.7.0',schema:'expert-validation/2.7',title:'Diagnóstico de startups en fases iniciales',researcherEmail:'luis.gonzalezc@urjc.es',
    purpose:'Ofrecer a las startups en fases iniciales y a quienes las acompañan o evalúan (inversores, mentores e incubadoras) un análisis de situación que permita identificar riesgos o debilidades, fortalezas y oportunidades.',
    population:'Startups en fases iniciales, desde la exploración de una idea hasta las primeras ventas y señales de repetición comercial.',
    source:'Instrumento V2.7 revisado el 17 de septiembre de 2026. Banco de 20 ítems; pendiente de validación experta.',
    expertCriteria:{relevance:'Relevancia de 1 a 4; obligatoria al enviar, salvo omisión explícita.',usability:'Claridad y respuestas, de 1 a 4; opcional para todos los ítems.'},
    dimensions:[
      {id:'D1',short:'Equipo',name:'Equipo',desc:'Capacidades, experiencia y conocimiento del sector, disponibilidad y aprendizaje del equipo para ejecutar el proyecto.'},
      {id:'D2',short:'Adaptación al mercado',name:'Adaptación al mercado',desc:'Comprensión del cliente, problema y mercado, diferenciación, monetización y evidencia de que la solución genera valor y puede evolucionar.'},
      {id:'D4',short:'Marketing y ventas',name:'Marketing y ventas',desc:'Evidencias de compromiso comercial y estrategia de lanzamiento, venta y aprendizaje en el proceso comercial.'},
      {id:'D5',short:'Gestión financiera',name:'Gestión financiera',desc:'Control de la situación financiera, previsión y gestión de caja y estimación de costes.'},
      {id:'D6',short:'Gestión de recursos y relaciones',name:'Gestión de recursos y relaciones',desc:'Relaciones externas y colaboraciones que aportan legitimidad y permiten acceder a recursos, conocimiento, mercado y oportunidades.'}
    ],
    items:[
      item('E1','D1','¿El equipo tiene los perfiles necesarios y complementarios para ejecutar el proyecto?',['No se ha analizado qué perfiles o capacidades necesita el proyecto.','Se conocen las principales carencias, pero algunas funciones críticas siguen sin cubrir.','Las funciones críticas están cubiertas y existe una persona responsable de cada una.','Todas las capacidades necesarias para llevar a cabo el proyecto están cubiertas y el equipo ha demostrado que puede ejecutar hitos relevantes.'],'Considerar áreas como producto, tecnología, operaciones, ventas u otras capacidades específicas del modelo de negocio. No es necesario que todas estén dentro del equipo fundador.'),
      item('E2','D1','¿El equipo conoce de primera mano al cliente, el sector y el problema que desea resolver?',['Las decisiones se basan principalmente en hipótesis internas.','Existe conocimiento indirecto o contacto ocasional con clientes o personas del sector.','El equipo tiene experiencia o contacto directo con el mercado y entiende cómo actúan, compran o resuelven actualmente el problema los clientes.','El equipo dispone de experiencia y conocimiento del mercado. Este conocimiento se actualiza regularmente y ya ha permitido corregir hipótesis o cambiar decisiones importantes.'],'No se exige experiencia profesional previa en el sector. El conocimiento puede obtenerse mediante experiencia, investigación o contacto continuado con clientes.'),
      item('E3','D1','¿La dedicación real del equipo (tiempo y foco) permite ejecutar las prioridades de esta fase?',['La falta de disponibilidad bloquea las prioridades principales.','Se pueden atender algunas prioridades, pero otras se retrasan de forma recurrente.','La disponibilidad es suficiente para ejecutar las prioridades actuales.','La dedicación se mantiene incluso ante periodos de mayor carga y permite cumplir los principales compromisos del proyecto.'],'Muchos inversores e incubadoras descartan proyectos por la falta de disponibilidad y foco del equipo. Aquí se evalúan ambos aspectos: la prioridad concedida al proyecto y la capacidad del equipo para ejecutar las acciones necesarias para que avance.'),
      item('E4','D1','¿El equipo escucha las señales del mercado: convierte la evidencia y los aprendizajes en decisiones sobre el proyecto?',['No se identifican aprendizajes o hipótesis concretas.','Se obtiene información y feedback, pero su impacto sobre las decisiones es limitado.','Las pruebas y aprendizajes se relacionan con decisiones concretas sobre el proyecto.','Los resultados se revisan sistemáticamente y las prioridades cambian cuando la evidencia contradice las hipótesis iniciales.'],'La evidencia puede proceder de entrevistas, uso, ventas, experimentos u operaciones. Lo importante es que influya en decisiones concretas.'),
      item('AM1','D2','¿Está claramente definido el segmento de clientes prioritario?',['El mercado objetivo es amplio y no existe un segmento concreto.','Se han identificado varios segmentos posibles, pero no existe una prioridad clara.','Existe un segmento prioritario definido con criterios que permiten identificar a sus clientes.','Existe un segmento prioritario. Las pruebas y acciones se concentran en ese segmento y su elección se revisa utilizando evidencias contrastadas.'],'Cuando sean diferentes, distinguir entre usuario, comprador y pagador.'),
      item('AM2','D2','¿Qué evidencia existe de que el problema es suficientemente importante como para que el cliente actúe?',['No hemos obtenido evidencia directa de clientes sobre este problema.','Los clientes reconocen el problema o dicen que les resulta relevante, pero no aportan ejemplos concretos ni muestran acciones para resolverlo.','Clientes del segmento objetivo describen situaciones reales en las que el problema les genera consecuencias relevantes, como pérdida de tiempo, costes, esfuerzo o riesgo.','En varios casos hemos observado que los clientes ya actúan para resolver el problema, dedicando tiempo, dinero, esfuerzo o utilizando soluciones alternativas.'],'Que un cliente diga que el problema le importa es una señal débil. La evidencia es más sólida cuando describe situaciones reales y, especialmente, cuando ya dedica tiempo, dinero, esfuerzo u otros recursos a resolverlo.'),
      item('AM3','D2','¿Se ha estimado cuántos clientes del segmento puede alcanzar realmente la startup?',['No existe una estimación del número de clientes potencialmente alcanzables.','Se manejan cifras generales de mercado, pero con pocos supuestos específicos sobre los clientes realmente accesibles.','Se ha estimado el número de clientes alcanzables considerando segmentos, geografía, canales y principales barreras de entrada.','La estimación se apoya en datos recientes o evidencia del mercado y se revisa cuando cambian los supuestos relevantes.'],'La estimación debería considerar el segmento objetivo, la geografía, los canales disponibles y las barreras de entrada. Evitar estimaciones basadas únicamente en aplicar porcentajes a grandes cifras de mercado.'),
      item('AM5','D2','¿Se conocen las principales alternativas en el mercado para nuestro cliente y existe una ventaja difícil de replicar?',['No se conocen suficientemente los competidores, sustitutos o alternativas actuales.','Se conocen las principales alternativas, pero la diferenciación es todavía una hipótesis o sería relativamente fácil de copiar.','Los clientes reconocen una ventaja concreta y replicarla requiere tiempo, conocimiento, recursos u otras capacidades relevantes.','Nuestra ventaja influye en decisiones reales de uso o compra y se apoya en varias barreras difíciles de reproducir.'],'No se exige una patente. La ventaja puede apoyarse en tecnología, datos, conocimiento especializado, marca, comunidad, red, acuerdos, costes de cambio u otros activos.'),
      item('AM4','D2','¿Se monitorizan los cambios del mercado que podrían afectar al éxito o fracaso del proyecto?',['No se realiza un seguimiento específico.','Se observan ocasionalmente tendencias, competidores o cambios relevantes.','Se revisan periódicamente clientes, competencia, tecnología, regulación, hábitos u otros cambios relevantes.','Se revisan las señales de forma sistemática, se relacionan con los resultados del producto y provocan cambios en la estrategia cuando es necesario.'],'Considerar cambios en clientes, competidores, tecnología, regulación, costes o hábitos. No basta con observarlos: deben relacionarse con decisiones del proyecto.'),
      item('AM6','D2','¿Está definido y contrastado quién paga, por qué paga y cómo lo hace?',['No está claro quién pagaría ni por qué concepto.','Existe una hipótesis sobre pagador, precio y forma de cobro.','La hipótesis se ha contrastado con posibles pagadores y se conocen sus principales objeciones.','Pruebas de oferta, negociación o venta han permitido ajustar el precio y las condiciones comerciales.'],'Cuando sean distintos, separar usuario, comprador y pagador. La forma de pago puede ser puntual, recurrente, por uso, por resultados u otra adecuada al modelo.'),
      item('AM8','D2','¿Las funcionalidades del producto o servicio se priorizan y mejoran utilizando evidencia de los usuarios?',['Las funcionalidades se deciden principalmente por intuición o ideas internas.','Existe una lista de funcionalidades y se recoge feedback, pero la priorización es poco sistemática.','Las funcionalidades se priorizan mediante criterios claros y utilizando feedback de usuarios.','Después de introducir cambios se comprueba su impacto y se vuelve a priorizar utilizando feedback, comportamiento o métricas.'],'Se evalúa si existe una priorización razonada basada en evidencia de usuarios, no el uso de una metodología concreta.'),
      item('MV1','D4','¿Qué grado de compromiso comercial real ha conseguido la startup?',['No existen compromisos comerciales documentados.','Existe interés, conversaciones o intenciones de compra, pero sin recursos comprometidos por parte del cliente.','Existen compras, pilotos, contratos u otros compromisos verificables de recursos.','Se observa repetición: nuevas ventas, renovaciones, compras recurrentes o repetición del proceso comercial con distintos clientes.'],'Una intención verbal tiene menos valor que dedicar tiempo, datos, recursos o dinero. Interesa la evidencia de comportamiento.'),
      item('MV2','D4','¿Se ha validado un canal de venta concreto para llegar al segmento prioritario y conseguir clientes?',['No existe una hipótesis concreta de canal o proceso comercial.','Existe una hipótesis sobre canal, mensaje y proceso de venta.','Se ha probado con clientes reales y se registran contactos, conversiones u otros resultados relevantes.','Pruebas sucesivas ofrecen resultados comparables y se conoce aproximadamente el tiempo y coste necesarios para conseguir clientes.'],'El canal de venta es la vía utilizada para llegar al cliente y convertir oportunidades en ventas. Adaptar las señales al ciclo comercial; en B2B complejo puede durar meses.'),
      item('MV3','D4','¿Se registran las oportunidades comerciales y las razones por las que avanzan, se detienen o se pierden?',['No existe un seguimiento estructurado de las oportunidades.','Se registran algunos contactos u oportunidades, pero de forma irregular.','Existe un seguimiento sistemático del estado de las oportunidades y de sus resultados.','Se analizan patrones de avance, pérdida y conversión y se utilizan para mejorar el proceso comercial.'],'No es necesario utilizar un CRM. Una hoja de cálculo puede ser suficiente si el seguimiento es consistente.'),
      item('GF1','D5','¿Se conoce el dinero disponible y los principales cobros y pagos de la startup?',['No se conoce con precisión la caja disponible o los principales movimientos.','Existen estimaciones aproximadas, pero no se actualizan de forma consistente.','La caja, cobros y pagos se registran y se conoce la situación financiera actual.','La información se actualiza periódicamente y se utiliza para decidir gastos y compromisos.'],'Se evalúa el control de caja necesario para decidir, no la existencia de una contabilidad sofisticada.'),
      item('GF2','D5','¿Existe una previsión que permita anticipar las necesidades financieras de los próximos meses?',['No existe una previsión.','Existe una estimación aproximada de ingresos y gastos futuros.','Existe una previsión de caja basada en supuestos explícitos y se conoce durante cuánto tiempo pueden mantenerse las operaciones.','La previsión se actualiza con datos reales y se utilizan diferentes escenarios para anticipar decisiones.'],'Una previsión de caja permite anticipar si habrá dinero suficiente para sostener las operaciones y tomar decisiones con tiempo.'),
      item('GF3','D5','¿Se conocen los recursos necesarios para alcanzar el siguiente hito objetivo de la startup y cómo se financiarán?',['No está definido el siguiente hito ni los recursos que requiere.','El siguiente hito está identificado, pero sus necesidades de recursos o financiación son aproximadas.','Se conocen los recursos necesarios, su coste y las principales fuentes para financiarlos.','Existe margen o un plan contrastado para financiar el hito y se revisa cuando cambian los resultados.'],'La financiación puede proceder de ventas, recursos propios, socios, deuda, ayudas o inversión. No se presupone que una startup deba captar capital riesgo.'),
      item('GF4','D5','¿Se ha estimado cuánto cuesta conseguir y atender a un cliente y qué margen genera?',['No se conocen suficientemente los costes o ingresos asociados a un cliente.','Existen estimaciones iniciales basadas principalmente en supuestos.','Existen datos o estimaciones contrastadas sobre adquisición, atención, ingresos y margen por cliente.','Estos datos se revisan periódicamente y se utilizan para tomar decisiones sobre precios, canales, costes o crecimiento.'],'CAC es el coste de adquirir un cliente y LTV es el valor que ese cliente genera durante la relación comercial. No es obligatorio utilizar estas métricas si no son adecuadas para el modelo de negocio.'),
      item('GR1','D6','¿La startup mantiene colaboraciones activas que le aportan recursos o ventajas concretas para avanzar?',['No existen colaboraciones relevantes.','Existen contactos o colaboraciones informales, pero aportan poco valor.','Existen colaboraciones activas que facilitan recursos, capacidades u oportunidades útiles para la startup.','Algunas colaboraciones generan ventajas claras y medibles y son relevantes para avanzar o crecer.'],'Evaluar el valor directo que aportan las colaboraciones, como acceso a conocimiento, tecnología, clientes, distribución, innovación, capacidades, eficiencia o reducción de costes.'),
      item('GR2','D6','¿La startup cuenta con clientes o colaboradores que refuerzan su credibilidad ante terceros?',['No existen todavía clientes o colaboradores que aporten una señal relevante de credibilidad.','Existen primeros clientes, pilotos o colaboraciones, pero aún generan pocas oportunidades adicionales.','La relación con algunos clientes o colaboradores reconocidos refuerza la credibilidad ante terceros y facilita acceso a recursos, contactos o nuevas oportunidades.','Estas relaciones generan de forma demostrable nuevas ventas, alianzas, distribución, financiación, conocimiento u otros recursos relevantes.'],'Evaluar si determinadas relaciones funcionan como señal de confianza y reducen la incertidumbre de futuros clientes, socios, inversores u otros actores relevantes.')
    ],glossary:[]
  };
  if(typeof module!=='undefined'&&module.exports)module.exports=instrument;else root.ValidationInstrument=instrument;
})(globalThis);
